### ISSUE TITLE
Improvement of error messages on missing extensions

### ISSUE THREAD

**Issue by reinerh** [d0c-s4vage/lookatme#111]
When a presentation is loaded that uses extensions that are not installed, lookatme will throw an exception:
```
Traceback (most recent call last):
  File "/usr/bin/lookatme", line 33, in <module>
    sys.exit(load_entry_point('lookatme==2.3.0', 'console_scripts', 'lookatme')())
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lookatme/__main__.py", line 122, in main
    pres = Presentation(
  File "/usr/lib/python3/dist-packages/lookatme/pres.py", line 54, in __init__
    self.reload(data=input_stream.read())
  File "/usr/lib/python3/dist-packages/lookatme/pres.py", line 102, in reload
    lookatme.contrib.load_contribs(
  File "/usr/lib/python3/dist-packages/lookatme/contrib/__init__.py", line 66, in load_contribs
    raise Exception(
Exception: Error loading one or more extensions:

No module named 'lookatme.contrib.qrcode'
```

To view it anyway, one could use the `-i` parameter.
It would be a bit nicer to give a better error message instead of a backtrace, like:
```
Extension 'qrcode' not found. Please install it or run with -i.
```

**Comment by d0c-s4vage** [comment]
Thank you for the suggestion!
