### ISSUE TITLE
lookatme can't find lookatme.contrib.image_ueberzug even though it is installed

### ISSUE THREAD

**Issue by vendion** [d0c-s4vage/lookatme#138]
**Describe the bug**
After installing `lookatme` and the `lookatme.contrib.image_ueberzug` extension, if I try to view a slide that uses it `lookatme` crashes.

**To Reproduce**

1. Install `lookatme`
2. Install `lookatme.contrib.image_ueberzug`
3. Try to view the tour slides.

**Expected behavior**
The slide deck to be viewable.

**Environment (please complete the following information):**
 - OS: Debian GNU/Linux 11
 - Lookatme Version: lookatme, version 2.3.0

**Additional context**
Stacktrace

```
    
                   _mBma
                  sQf "QL
                 jW(   -$g.
                jW'     -$m,
              .y@'  _aa.  4m,
             .mD`  ]QQWQ.  4Q,
            _mP`   ]QQQQ    ?Q/
           _QF     )WQQ@     ?Qc
          <QF       QQQF      )Qa
         jW(        QQQf       "QL
        jW'         ]H8'        -Q6.
      .y@'          _as.         -$m.
     .m@`          ]QQWQ.         -4m,
    _mP`           -?$8!            4Q,
    mE                               $m
    ?$gyygggggggggwywgyygggggggygggggD(
    
New extensions required by 'slides.md' are about to be loaded:

  - 'lookatme.contrib.image_ueberzug'
  - 'lookatme.contrib.terminal'

Are you ok with attempting to load them? (Y/N) y
Traceback (most recent call last):
  File "/usr/bin/lookatme", line 33, in <module>
    sys.exit(load_entry_point('lookatme==2.3.0', 'console_scripts', 'lookatme')())
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/lookatme/__main__.py", line 122, in main
    pres = Presentation(
  File "/usr/lib/python3/dist-packages/lookatme/pres.py", line 54, in __init__
    self.reload(data=input_stream.read())
  File "/usr/lib/python3/dist-packages/lookatme/pres.py", line 102, in reload
    lookatme.contrib.load_contribs(
  File "/usr/lib/python3/dist-packages/lookatme/contrib/__init__.py", line 66, in load_contribs
    raise Exception(
Exception: Error loading one or more extensions:

No module named 'lookatme.contrib.image_ueberzug'
```

ueberzug install locations (installed via [these instructions](https://github.com/d0c-s4vage/lookatme.contrib.image_ueberzug#installation)
```
find / -name 'ueberzug' 2>/dev/null
/home/vendion/.local/lib/python3.9/site-packages/ueberzug
/home/vendion/.local/bin/ueberzug
/usr/local/bin/ueberzug
/usr/local/lib/python3.9/dist-packages/ueberzug
```

**Comment by d0c-s4vage** [comment]
Is this part of a pipx installation?

In the same environment that you're running the presentation from, are you able to import that module? Like this:

```
python3 -c "import lookatme.contrib.image_ueberzug"
```

If it imports successfully, it won't print anything. If it can't import it, you'll see this error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'lookatme.contrib.image_ueberzug'
```
