### ISSUE TITLE
Installation not working on Windows

### ISSUE THREAD

**Issue by GloriousGlider8** [d0c-s4vage/lookatme#222]
**Describe the bug**
`pip install lookatme` is not working on Windows.
The Error:
```
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output
```
If you wish to see the output, scroll to the bottom.
**To Reproduce**

1. Use **[WINDOWS] + [R}**
2. Type `cmd`
3. Press [ENTER]
4. Run the command `pip install lookatme`

**Expected behavior**
I expected lookatme to be installed.

**Environment (please complete the following information):**
 - OS: Windows 11 Home
 - Lookatme Version: **N/A**
 -
# Output
## [USERNAME] represents my Windows username
```Collecting lookatme
  Using cached lookatme-2.5.5-py3-none-any.whl (42 kB)
Requirement already satisfied: marshmallow<4,>=3.17.0 in c:\users\[USERNAME]\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from lookatme) (3.20.1)
Requirement already satisfied: Click<9,>=7 in c:\users\[USERNAME]\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from lookatme) (8.1.7)
Collecting PyYAML<6,>=5 (from lookatme)
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-rbwdc_sd\overlay\Lib\site-packages\setuptools\config\setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!

              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.

              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running egg_info
      writing lib3\PyYAML.egg-info\PKG-INFO
      writing dependency_links to lib3\PyYAML.egg-info\dependency_links.txt
      writing top-level names to lib3\PyYAML.egg-info\top_level.txt
      Traceback (most recent call last):
        File "C:\Users\[USERNAME]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\[USERNAME]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\[USERNAME]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-rbwdc_sd\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-rbwdc_sd\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-rbwdc_sd\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-rbwdc_sd\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-rbwdc_sd\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-rbwdc_sd\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-rbwdc_sd\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-rbwdc_sd\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-rbwdc_sd\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-rbwdc_sd\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 318, in run
          self.find_sources()
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-rbwdc_sd\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 326, in find_sources
          mm.run()
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-rbwdc_sd\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 548, in run
          self.add_defaults()
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-rbwdc_sd\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 586, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-rbwdc_sd\overlay\Lib\site-packages\setuptools\command\sdist.py", line 113, in add_defaults
          super().add_defaults()
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-rbwdc_sd\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-rbwdc_sd\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 201, in get_source_files
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-rbwdc_sd\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
```

**Comment by AFKBETO** [comment]
I have the same issue when installing on Win11. Is there any workaround for the issue? I tried downgrading pyYAML but that does not work...

```
Collecting lookatme
  Using cached lookatme-2.5.5-py3-none-any.whl (42 kB)
Requirement already satisfied: marshmallow<4,>=3.17.0 in c:\python312\lib\site-packages (from lookatme) (3.20.1)
Requirement already satisfied: Click<9,>=7 in c:\python312\lib\site-packages (from lookatme) (8.1.7)
Collecting PyYAML<6,>=5 (from lookatme)
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib3\PyYAML.egg-info\PKG-INFO
      writing dependency_links to lib3\PyYAML.egg-info\dependency_links.txt
      writing top-level names to lib3\PyYAML.egg-info\top_level.txt
      Traceback (most recent call last):
        File "C:\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-im7pucbr\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-im7pucbr\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-im7pucbr\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-im7pucbr\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-im7pucbr\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-im7pucbr\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-im7pucbr\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-im7pucbr\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-im7pucbr\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-im7pucbr\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 321, in run
          self.find_sources()
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-im7pucbr\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 329, in find_sources
          mm.run()
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-im7pucbr\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 551, in run
          self.add_defaults()
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-im7pucbr\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-im7pucbr\overlay\Lib\site-packages\setuptools\command\sdist.py", line 112, in add_defaults
          super().add_defaults()
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-im7pucbr\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-im7pucbr\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "C:\Users\[USERNAME]\AppData\Local\Temp\pip-build-env-im7pucbr\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
WARNING: Ignoring invalid distribution ~ookatme (C:\Python312\Lib\site-packages)
```

**Comment by nkxxll** [comment]
I have the same problem, same error:

OS: Windows - WSL2
Python: conda python version - Python 3.11.8

**Comment by jmgonzalezro** [comment]
Same error same problem in arch linux. Trying to build directly from pacman.
